### ISSUE TITLE
Strange dotting patterns after recent changes

### ISSUE THREAD

**Issue by jvgaultney** [simoncozens/Dotter#14] opened 2023-12-12 10:21 UTC
Recent changes are resulting in some odd dotting patterns:

![image](https://github.com/simoncozens/Dotter/assets/4226750/848e96a8-b16d-4433-bfab-e87981d47041)

This is using font-pendot-latin with the following settings:

userData = {
co.uk.corvelsoftware.Dotter = {
dotSize = 60;
dotSpacing = 40;
preventOverlaps = 1;
splitPaths = 1;
};

**Comment by jvgaultney** [comment] 2023-12-12 10:23
This is only in the build not preview

**Comment by simoncozens** [comment] 2023-12-12 12:20
I think 10fa4db fixed that.

**Comment by jvgaultney** [comment] 2023-12-12 13:30
This was using a fresh clone of Dotter this morning, so past that commit.

**Comment by simoncozens** [comment] 2023-12-13 14:59
It looks like a few days ago you [committed](https://github.com/silnrsi/font-pendot-latin/commit/7342baf8ec0f5d348e2a7cec9bcbdbf3f1369d97) a frozen `requirements.txt`, so your builds will take Dotter a at 177c207.

**Comment by jvgaultney** [comment] 2023-12-13 16:47
Ah - that would explain it! But I did that to fix the glyphsLib path bug. How can I freeze glyphsLib with:

`glyphsLib @ git+https://github.com/googlefonts/glyphsLib@1da0b185d280e4c74a40b33cfcbcbe6457ba6ed9`

WIthout the pendot/Dotter freeze (which some tool must have generated - I didn't specify the freeze myself)?

I'm unsure how that requirements.txt file gets generated or what it should ideally contain. I just took the file that was currently in my local repo, added the glyphsLib fix, and committed the file.

**Comment by simoncozens** [comment] 2023-12-13 19:03
*For now*, requirements.txt should contain:

```
pendot @ git+https://github.com/simoncozens/Dotter/
glyphsLib @ git+https://github.com/googlefonts/glyphsLib@segments-again
gftools @ git+https://github.com/googlefonts/gftools@builder2

fontmake>=2.4
drawbot-skia>=0.4.8
sh>=1.14.2
bumpfontversion>=0.2.0
diffenator2>=0.2.5
```

When we're happy with everything we should check in the frozen file, but for now, please avoid checking in any other changes made to this file. (The "first-run script" freezes on build. To avoid that, create a file called `.init.stamp` in your working directory.)

**Closed** 2023-12-14 07:04 UTC

**Comment by jvgaultney** [comment] 2023-12-14 10:38
I'm still confused about what is going on. I replaced requirements.txt with what you recommended and checked that in. I ran `make clean` and `make build`, which changes requirements.txt. So now my local requirements.txt is different from what is checked in, and has now frozen pendot, glyphsLib, and gftools to specific commits. Excerpt:

```
gftools @ git+https://github.com/googlefonts/gftools@4551081475be99ec3da7c6c236aca2d16b182230
gitdb==4.0.11
GitPython==3.1.40
glyphsets==0.6.8
glyphsLib @ git+https://github.com/googlefonts/glyphsLib@1da0b185d280e4c74a40b33cfcbcbe6457ba6ed9
h11==0.14.0
hyperglot==0.4.5
idna==3.6
Jinja2==3.1.2
lxml==4.9.3
markdown-it-py==3.0.0
MarkupSafe==2.1.3
mdurl==0.1.2
MutatorMath==3.0.1
nanoemoji==0.15.1
networkx==3.2.1
ninja==1.11.1.1
numpy==1.26.2
openstep-plist==0.3.1
opentype-sanitizer==9.1.0
orjson==3.9.10
outcome==1.3.0.post0
packaging==23.2
pendot @ git+https://github.com/simoncozens/Dotter/@80c443ea636d206374bf5611e2c59e2f0b0fd4ec
```
All of this time I've had an `.init.stamp` and `build.stamp` in my working directory.

**Comment by jvgaultney** [comment] 2023-12-14 10:53
The end of my build log in which this file gets changed:

```
. venv/bin/activate; python3 scripts/first-run.py
Fixing URLs: https://googlefonts.github.io/googlefonts-project-template -> https://silnrsi.github.io/font-pendot-latin.git
Fixing URLs: https%3A%2F%2Fraw.githubusercontent.com%2Fgooglefonts%2Fgooglefonts-project-template -> https%3A%2F%2Fraw.githubusercontent.com%2Fsilnrsi%2Ffont-pendot-latin.git
Fixing URLs: https://yourname.github.io/your-font-repository-name -> https://silnrsi.github.io/font-pendot-latin.git
Pinning dependencies
rm -rf fonts
(for config in sources/config*.yaml; do . venv/bin/activate; gftools builder $config; done)  && touch build.stamp
[1/3] buildTTF
fontmake --output-path /var/folders/63/wvw734f103zck80xqfhcsqr80000gn/T/tmpai63etz0 -o ttf -g build/PendotL-Dotted.glyphs --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
[2/3] rename
gftools-rename-font -o /var/folders/63/wvw734f103zck80xqfhcsqr80000gn/T/tmpjd8iwh2q /var/folders/63/wvw734f103zck80xqfhcsqr80000gn/T/tmpai63etz0 Pendot Latin Test Dotted
[3/3] fix
gftools-fix-font -o ../fonts/ttf/PendotLTestA-Dotted.ttf /var/folders/63/wvw734f103zck80xqfhcsqr80000gn/T/tmpjd8iwh2q

```

**Comment by jvgaultney** [comment] 2023-12-14 11:13
BTW - the original problem with strange dotting patterns is now fixed, but I'd still like to understand better what I'm supposed to do with requirements.txt to keep it from freezing those three repos.

**Comment by simoncozens** [comment] 2023-12-14 11:37
The googlefonts-project-repository works well in the normal situation: when you start building a font, you want reproducible builds, you don't want your toolchain to change underneath you, so it makes sense to freeze the project requirements on first build. This situation is emphatically not the normal situation because we are building the toolchain as we go along, so we don't want freezing to happen yet! So we are doing something a bit custom, and we should edit our Makefile accordingly.

In the stock `Makefile`, the freezing happens here:

```
.init.stamp: venv
    . venv/bin/activate; python3 scripts/first-run.py
```

and this should only be called if `.init.stamp` is newer than the venv directory. Again, that's not a bad idea in the normal situation - if someone updates dependencies, we should freeze them again.

In our distinctly non-normal situation, I recommend we delete these two lines, and also the reference to `.init.stamp` on line 23, and then freeze manually when we are happy with the toolchain.

**Comment by jvgaultney** [comment] 2023-12-14 16:12
Thanks - I've done that now.
